apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio
  template:
    metadata:
      labels:
        app: microservicio
    spec:
      containers:
      - name: microservicio
        image: ghcr.io/rwangnet/microservicio:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: microservicio
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: microservicio