name: CI/CD Pipeline

on:
  push:
    branches:
      - feature-ms-ricardoWangnet-mensaje

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
     ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
     SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}

    steps:
      # Checks current branch code
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets in the current GH container the java version for building the application
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: "temurin"
          java-version: "8"

      # Runs the current Maven build command to generate Java artifacts
      - name: Build with Maven
        run: mvn -B clean package

      # Sets in the current GH container the java 17 version for building the application
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Sonarcloud Analysis
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=rwangnet \
          -Dsonar.projectKey=rwangnet_microservicio-java

      # Set up buildx docker CLI in container.
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Login to GHCR to push the docker image
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rwangnet
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and pushes docker image to GHCR
      - name: 'Build and Push Docker Image to GHCR'
        run: |
            docker build . --tag ghcr.io/rwangnet/microservicio:latest
            docker push ghcr.io/rwangnet/microservicio:latest